apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: a87cd590d02570f6dc744bc6f81d56d000779541
        name: go-server-ci
